Install cypress and first test
Esmorga-Backend/esmorga-backend pull request #13
Opened 2024-05-21 12:30 UTC by YagoAres

2024-05-21 13:33 UTC, LetiRocha requested changes

2024-05-21 13:33 UTC, LetiRocha commented on test-e2e/cypress/support/commands.js
> +// This example commands.js shows you how to
Don't add classes with comments only

2024-05-21 13:33 UTC, LetiRocha commented on test-e2e/cypress/support/e2e.js
> +// ***********************************************************
same, don't add classed with only commented code, cause this only includes a reference to the previous one that is only commented code

2024-05-21 13:33 UTC, LetiRocha commented on test-e2e/cypress/fixtures/example.json
> +{
this is not being used anywhere either

2024-05-22 08:50 UTC, LetiRocha requested changes
Please rename the file of the initial test to follow the naming standar in the rest of the project

2024-05-22 10:11 UTC, LetiRocha commented on test-e2e/cypress.config.js
> +    baseUrl: 'https://qa.esmorga.canarte.org/', //URL base de la aplicación
I don't think that comment is needed

2024-05-22 10:11 UTC, LetiRocha commented on test-e2e/cypress.config.js
> +    supportFile: false //Archivo de soporte no necesario
comments should be in english as the rest of the code

2024-05-22 10:12 UTC, LetiRocha commented on test-e2e/cypress/e2e/1test.spec.js
> +  //Test de prueba para verificar que todo está funcionando correctamente
This comments doesn't bring any value

2024-05-22 10:24 UTC, LetiRocha approved these changes

2024-05-22 11:16 UTC, LetiRocha approved these changes

2024-05-22 12:47 UTC, YagoAccenture approved these changes

2024-05-22 14:24 UTC, PabloCanarteSol approved these changes

2024-05-22 14:29 UTC, merged