[MOB-39] Cucumber over Jest Setup
Esmorga-Backend/esmorga-backend pull request #30
Opened 2024-06-06 07:17 UTC by PabloCanarteSol

## Pull Request Checklist

- [ ] **Title**
- [ ] **MOB US' Link**
- [ ] **Link PR to US**
- [ ] **Add Tests**
- [ ] **Add ENV Variables and Validations**
- [ ] **Check Story Points**
- [ ] **Documentation Updates**
- [ ] **Swagger Updates**

## Testing Guide

2024-06-11 16:47 UTC, LetiRocha requested changes

2024-06-11 16:47 UTC, LetiRocha commented on test/scripts/features-update.js
> +//    const outputDir = path.resolve(__dirname, 'extracted');
Entiendo que esto sobra

2024-06-11 16:47 UTC, LetiRocha commented on test/scripts/features-update.js
> +if (!fs.existsSync(outputDir+'/MOB_Feature.feature')) {
is this comment needed?

2024-06-11 16:47 UTC, LetiRocha commented on test/jest-component/features/steps/events/get-events-steps.ts
> +
Is this code formatted? I see empty lines with no clear pattern

2024-06-11 16:47 UTC, LetiRocha commented on test/jest-component/features/steps/events/get-events-steps.ts
> +        expect(false).toBe(true)
I don't understand why you need that sentence, can you explain?

2024-06-11 16:47 UTC, LetiRocha commented on test/jest-component/features/steps/events/get-events-steps.ts
> +    and(/^(\d+) Events in DB, (\d+) are in the past$/, (events_on_db,expired_events_on_db) => {
The last if seems incorrect (or at least I don't understand it). Plus, the whole block looks quite complex, there are several ways to improve it I guess. One possibility could be: using a variable for  N expired events and a variable for M upcoming events and then prepare the array for the mock in just two loops, one for adding oldEventMock from 0 to N and another one for adding futureEventMockDB from 0 to M. Afterwards, just have one sentence to prepare the mock with the array.  In this way you can add new combinations without modifying the code

2024-06-11 16:47 UTC, LetiRocha commented on test/jest-component/features/steps/events/get-events-steps.ts
> +      if (events_to_check == 1){
this block I guess it can be improved, using the variable for events to prepare the expected result, so you can add more variations without having to modify the code

2024-06-12 07:03 UTC, PabloCanarteSol commented on test/scripts/features-update.js
> +//    const outputDir = path.resolve(__dirname, 'extracted');
Removed in next commit "fix pull request comments & event repo"

2024-06-12 07:03 UTC, PabloCanarteSol commented on test/scripts/features-update.js
> +if (!fs.existsSync(outputDir+'/MOB_Feature.feature')) {
Removed in next commit "fix pull request comments & event repo"

2024-06-12 07:07 UTC, PabloCanarteSol commented on test/jest-component/features/steps/events/get-events-steps.ts
> +
```
then(/^the response should contain (\d+) upcoming Events$/, ( events_to_check) => {
...
      expect(response.body).toMatchObject(
        {"totalEvents": parseInt(events_to_check)}
      )
```
Other way it always create the example to match :
{"totalEvents": "1"}
and I need it as 
{"totalEvents": 1}

2024-06-12 10:15 UTC, LetiRocha approved these changes

2024-06-12 12:17 UTC, merged